import {
  DEPLOY_TARGET,
  PRODUCTION_FIREBASE_API_KEY,
  PRODUCTION_FIREBASE_AUTH_DOMAIN,
  PRODUCTION_FIREBASE_PROJECT_ID,
  STAGING_FIREBASE_API_KEY,
  STAGING_FIREBASE_AUTH_DOMAIN,
  STAGING_FIREBASE_PROJECT_ID,
} from './env'

export const FIREBASE_OPTIONS = (() => {
  if (DEPLOY_TARGET === 'production') {
    return {
      apiKey: PRODUCTION_FIREBASE_API_KEY,
      authDomain: PRODUCTION_FIREBASE_AUTH_DOMAIN,
      projectId: PRODUCTION_FIREBASE_PROJECT_ID,
    }
  }

  return {
    apiKey: STAGING_FIREBASE_API_KEY,
    authDomain: STAGING_FIREBASE_AUTH_DOMAIN,
    projectId: STAGING_FIREBASE_PROJECT_ID,
  }
})()

export const FIRESTORE_EMULATOR_PORT = 8080

export const FIRE_AUTHENTICATION_EMULATOR_PORT = 9099
